title: "Pankaj K. Mishra"
description: "Pankaj K. Mishra - Assistant Professor, Department of Electrical Engineering, NIT Hamirpur. Research in nonlinear control, constrained systems, approximation-free control and adaptive control."
url: "https://p-k-mishra.github.io"
baseurl: ""
email: "pmishra@nith.ac.in"
profile_image: "/assets/images/profile.jpg"
cv_url: "https://drive.google.com/file/d/10WOdCxXi2E4L8yb0O4mQFAP32zgaMJrr/view?usp=share_link"
markdown: kramdown
permalink: /articles/:year/:month/:day/:title/
future: false

social:
  scholar: "https://scholar.google.com/citations?user=0U00q7MAAAAJ&hl=en"
  researchgate: "https://www.researchgate.net/profile/Pankaj-Mishra-18"
  linkedin: "https://www.linkedin.com/in/pkmishra1991"
  github: "https://github.com/p-k-mishra"
  whatsapp: "https://api.whatsapp.com/send/?phone=919101514943&text&type=phone_number&app_absent=0"
  orcid: "https://orcid.org/0000-0003-4037-6769"

exclude:
  - README.md
